#pragma once

// This file is generated by xy_robotkit.
// Do not edit this file manually.

#include "main.h"
#include "DataBus.hpp"
#include "BMI088Sensor.hpp"
#include "MS5837Sensor.hpp"
#include "IST8310Sensor.hpp"
#include "MahonyAHRS.hpp"
#include "PIDController.hpp"
#include "PCA9685ThrusterModule.hpp"
#include "MotorControl.hpp"
#include "Communication.hpp"
#include "Protocol.hpp"

static BMI088Sensor     imu(5, "3G", "2000");
static MS5837Sensor     depth_sensor(997, 100);
static IST8310Sensor    ist8310(10);
static MahonyAHRSModule ahrs(200.0f, 5.0f, 0.0f);
static PIDController     pid;       // no-op, included for completeness
static PCA9685ThrusterModule pca9685;
static MotorControl      motor_control;
static Communication     comm;

inline void XYRobotSetup() {
    imu.Init();
    depth_sensor.Init();
    ist8310.Init();
    ahrs.Init();
    pca9685.Init();
    motor_control.Init();
    comm.Init();
}

inline void XYRobotLoop() {
    // 1. Sensor acquisition
    imu.Update();             // -> robot.accel, robot.gyro
    depth_sensor.Update();    // -> robot.depth_m (every 100ms)
    ist8310.Update();         // -> robot.mag (every 10ms)

    // 2. Attitude estimation
    ahrs.Update();            // gyro/accel/mag -> robot.quat, yaw/pitch/roll, *_v

    // 3. Communication
    comm.Update();            // USART6 -> robot.target_*, robot.flags

    // 4. Motor control
    motor_control.Update();   // sensors/targets -> PID cascade -> robot.pwm[8]

    // 5. Actuator output
    pca9685.Update(HAL_GetTick());

    HAL_Delay(5);
}
