# Auto-generated by xy_robotkit. Do not edit.
# Include this in your CMakeLists.txt to add all modules to the build.
#
# Usage:
#   include(xy_robot_modules.cmake)
#   target_sources(${PROJECT_NAME} PRIVATE ${XY_ROBOT_MODULE_SOURCES})
#   target_include_directories(${PROJECT_NAME} PRIVATE ${XY_ROBOT_MODULE_INCLUDES})

file(GLOB MODULE_SRC_DIRS "Modules/*/src")
file(GLOB MODULE_INC_DIRS "Modules/*/include")

foreach(mod_src ${MODULE_SRC_DIRS})
    file(GLOB_RECURSE MOD_SOURCES "${mod_src}/*.c" "${mod_src}/*.cpp")
    list(APPEND XY_ROBOT_MODULE_SOURCES ${MOD_SOURCES})
endforeach()

foreach(mod_inc ${MODULE_INC_DIRS})
    list(APPEND XY_ROBOT_MODULE_INCLUDES ${mod_inc})
endforeach()

# Also scan root-level legacy modules (含 xy_module.yaml 的目录)
file(GLOB ROOT_MODULES RELATIVE "${CMAKE_CURRENT_SOURCE_DIR}" "*")
foreach(mod ${ROOT_MODULES})
    if(IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/${mod}" AND EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/${mod}/xy_module.yaml")
        if(IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/${mod}/src")
            file(GLOB_RECURSE LEGACY_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/${mod}/src/*.c" "${CMAKE_CURRENT_SOURCE_DIR}/${mod}/src/*.cpp")
            list(APPEND XY_ROBOT_MODULE_SOURCES ${LEGACY_SOURCES})
        endif()
        if(IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/${mod}/include")
            list(APPEND XY_ROBOT_MODULE_INCLUDES "${CMAKE_CURRENT_SOURCE_DIR}/${mod}/include")
        endif()
    endif()
endforeach()

# Remove duplicates
if(XY_ROBOT_MODULE_SOURCES)
    list(REMOVE_DUPLICATES XY_ROBOT_MODULE_SOURCES)
endif()
if(XY_ROBOT_MODULE_INCLUDES)
    list(REMOVE_DUPLICATES XY_ROBOT_MODULE_INCLUDES)
endif()
